# SPDX-License-Identifier: LGPL-3.0-or-later
name: CI
on: [push, pull_request]
jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: latest
      - run: pixi run build
      - run: pixi run test
      - run: pixi run lint
